### ISSUE TITLE
Cannot supply needed credentials for mqtt broker

### ISSUE THREAD

**Issue by Hermarcel** [EvensSolutions/hass-victron-mqtt-discovery#7]
I installed the Home Assistant AddOn. It starts ok, but seems to freeze at:

`s6-rc: info: service s6rc-oneshot-runner successfully started`
`s6-rc: info: service fix-attrs: starting`
`s6-rc: info: service fix-attrs successfully started`
`s6-rc: info: service legacy-cont-init: starting`
`s6-rc: info: service legacy-cont-init successfully started`
`s6-rc: info: service legacy-services: starting`
`s6-rc: info: service legacy-services successfully started`
`[20:10:09] INFO: Loading python environment`
`[20:10:09] INFO: Setting up configuration`
`[20:10:10] INFO: Starting discovery`

From the Home Assistant Mosquitto broker log:

`2025-05-25 20:10:14: New connection from 172.30.33.5:34847 on port 1883.`
`error: received null username or password for unpwd check`
`2025-05-25 20:10:15: Client auto-5FE6AFD3-DD6F-7D31-7A94-88850F7ADF52 disconnected, not authorised.`

I looked into your code briefly, but it seems that only anonymous access is implemented?

How do I proceed?

**Comment by JorgenEvens** [comment]
I've released `v0.1.4` that supports the `MQTT_USERNAME` and `MQTT_PASSWORD` environment variables, as well as the settings configured in the Home Assistant MQTT addon.

**Comment by JorgenEvens** [comment]
If you are using the Home Assistant Addon, you might want to skip `v0.1.4` and use `v0.1.5` as I forgot to update the version in the addon config in `v0.1.4`.

**Comment by Hermarcel** [comment]
Using v0.1.5::

The line in the mosquitto log:
error: received null username or password for unpwd check
is gone, but
2025-05-30 22:16:18: New connection from 172.30.33.4:55767 on port 1883.
2025-05-30 22:16:18: Client auto-EA36B0B6-11C0-6B6E-AADA-F11F0B44F964 disconnected, not authorised.
still appears in the Mosquitto log...

So, it's not succesful yet.
